version: 1
disable_existing_loggers: False
formatters:
  brief:
    format: '%(levelname)-8s %(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

# For more information see https://docs.python.org/3.7/library/logging.config.html.

# ---------------------
# | Level   | Numeric |
# ---------------------
# | CRITICAL| 50      |
# | ERROR   | 40      |
# | WARNING | 30      |
# | INFO    | 20      |
# | DEBUG   | 10      |
# | NONSET  | 0       |
# ---------------------

handlers:
  brief_console:
    class: logging.StreamHandler
    formatter: brief
    stream: ext://sys.stdout
  default_console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  # info_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: INFO
  #   formatter: default
  #   filename: info.log
  #   maxBytes: 10485760
  #   backupCount: 20
  #   encoding: utf8
  # error_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: ERROR
  #   formatter: default
  #   filename: errors.log
  #   maxBytes: 10485760
  #   backupCount: 20
  #   encoding: utf8

loggers:
  textractutil.parser:
    level: INFO
    handlers: [brief_console]
    propagate: no 
  textractutil.input_validator:
    level: INFO
    handlers: [brief_console]
    propagate: no 

# root:
#   level: ERROR
#   handlers: [info_file_handler, error_file_handler]